############################
### WAN INTERFACE IPV6 RA OVERRIDES (template)
############################
# Replace IFWAN with the actual WAN interface name during deployment.
# Make sure that noipv6rs is set in dhcpcd
# These settings allow the WAN interface to behave like a host so it can:
# - Accept Router Advertisements from the ISP
# - Autoconfigure its IPv6 address (SLAAC)
# - Install the upstream default IPv6 route
# - Receive prefix information (PIO)
# - Receive router preference and RDNSS info
net.ipv6.conf.IFWAN.accept_ra                = 1
net.ipv6.conf.IFWAN.autoconf                 = 1
net.ipv6.conf.IFWAN.accept_ra_defrtr         = 1
net.ipv6.conf.IFWAN.accept_ra_pinfo          = 1
net.ipv6.conf.IFWAN.accept_ra_rtr_pref       = 1
