[Unit]
# wait for dhcpcd service
Wants=dhcpcd.service
After=dhcpcd.service

[Service]
# this service can take up to 60 seconds to start
TimeoutStartSec=60
# wait for the network to be connected
ExecStartPre=/usr/local/bin/network-connected.sh 30 dual IFLAN

# disable dnsmasq's resolvconf integration (removes ExecStartPost/ExecStop from vendor unit)
ExecStartPost=
ExecStop=
